language: node_js

node_js:
  - "4.0"
  - "4"
  - "5"

env:
  matrix:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master
    - "/^feature-.*$/"
    - "/^hotfix-.*$/"
    - "/^test-.*$/"

sudo: false
