language: node_js
node_js:
- '6'
sudo: false
script:
- npm run build
- npm test
- mkdir tmp
- cp lib/browser/index.release.js tmp/element-dataset.js

env:
  global:
  - CXX=g++-4.8
  - secure: TA22HAlRCmNAje5/5l3/zQdiG47uUvbBzNd9DXc9KdruxgQFhT+5dcbXs4kXX1nj6fYbOg/xHRihe9Wr7I7GjoV7Jl7235oZDbjG6q9nEM/zKi7/AJiED+vwi1+Sq649AKkulUdkKf6i2s7IVMiFbKySc799+PD2LFYSysJ9KdpPfnnepEkJiJOesKBrXsWp8moddUzCAnSRlG+O/3Cjc0u34DCfbmu7NPxamO8SP+GlJRrxggZAMSRssO1OMAft2sCJiE8SnbUDDTjR+0/+yfl3xzBrWkt8SvKylB7utiyAwEWbEoi3rjRTfQ+Ax5lykm2TxrQ1RRSlMCequQMpK2qYvjKj3JbHVCidBIbJvQOVC1ltse67Uz0IUxx3HjQVmRoWx4TqIvDbaa1wpnTERiei9i/BC1oJC+EzkLUncX7hn42Rn/1dgJbW0xWYrHYoicU1/OTkutUAEj2pvbzNqyYikbDkvh2HUnM00aCYm97jLg8RTbproieg5u+Qe/eLIVrnlxn3yMZtKkUhzhG1UQXSik7KIjfCr9mYXO0h3s249ppjA9jdoVt11D0hFR5KEU2WTTH1Of99VEsyXDsQSZ3jbaBzzo56ENHNqoyAXl/BDXyZymarIfPBhcDekNhPDKH80xDawNanvSL3737xY6MzVzuIi/HO9vvEW7Yhcd4=
  - secure: sVoEEhESD5u0eBZ4EOTbk6RdXTnqjpcyRgsk82aXTXn9o6ILcQgXW3HDdiZ0UoGlA0SXs70ZWigYFZBBVnvpcImy/8BLP1riLl0BGaxc/OZKvXuNYIio53+VxMln3juSHQKtYamkA7fB88zvZ/5SQcQ9kGFDYptbSXnVZfqGKIll/s6cJU3SOFXWjx4tw5Zv2fWRAeoUKJnX67sf/9pNFjlmAlhZdaKzYh+Q/FGy+99eXywc+u9FPh/LFZozVwcFMQbyEddZwrxcJswzyvpcDP2ncSvwZJBpWBoIfZ9oSjR3sWUt6W+p1dMml4qOp0Z2Ply2OgMBdhXQSm6k2mIOhj6UuhbrvnW6k7QAW8NjK5R5hg0mobLfKdYsHrqNrOA8KC6hA80ok0KRUZ2R0JGW7cgilVujyvuGK9zttHeDdI9emahucUUsmjLc6DjnfoPV2eOcow1X1PJggkzQHv3BpaGYZ99wAFedD6gV+YUMliU8Rq27NFWhVLJHyi/J4MNolgRmUznTWkYCYbDOY8UV2b0T2ELWT+a7EGuiablU28ylZbMFJORuuABg1lNIYqcSzw0bsnuy3W0Rzj2QGws4a+10XYL3Afaxj9DPvxxV2UIEK80M3vLaK1inwq+7TUR+CVWaRWmSxuOFibK0VWq4ZpHyifLz1jdidlvlpeWQ5vc=

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

deploy:
  - provider: releases
    api_key:
      secure: o0a95Ezu7w8IM55/GVsbkcd8wnfzcw3NJH7eFg8QRjEXoFa4iuEkWyBK1/c9JimQ/uCEUR7I0bb0fvHsfNBv1qbUpYBUMxac4cGSqP6Zp+4mmnZ1jzr9bpVHWzhXz6UvyWB5EhctdsiiQr4vKd4wJ4Di5J8Vac7YmpakuOu09nVASWfhkPCEyb3FxKbhzXdeaNNnhh1hylFl+mTMSI0503T5MWZPk774wIdIE4xvwFdRK9Fc8g3Gv4R1Wv4L6hEmimqUGoFKOqrLICrhJwjTLYgIVuawKtxdQZlT0Q6n/OiXVbcSmSQmIeMKtbYVTNPoTo7lY4UhgBT+OFAPEX2OrvW+SLjYUuimNLWsXc5MaK9TxHcGJkCdsh8JjYVlX3d8uUypXL5A0Ug3eo2RaHkTJ5TP1vmXZdvt5ybqmy6cDJAfU8khuUUWs5B8uSOhe9BYtaQrbWEv9Yqlyc4fLAdkXixE2Nva5ky31PoWADIL0ySSg8uhf8ITavdySbQVmb1OnSTiD9b2jSL84fem6C9x2m3a0Ffy8X16ZGGIaGC4FLAS9Y6oZ7nVf2Pwr8V0ItiFuf2CmoTuQuTPOIxLNZiJ8IVklv1HwzX9Qhb00SdZF1nqJP7pjTrKa418GFNSeFJObab3EABdOCD6uJqNUtcGtIxcsq94B3KkDy5wKHG+kps=
    file: "tmp/element-dataset.js"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: robots+npm@epiloque.com
    api_key:
      secure: ewxDPbrYc60wjMKT+nt+mXenSevcJtYmkmKYSXLjcC7gzlVuaLBjSA/ZdLyia0gst/C4enjWc3hW+jOui5dgMXb+zlTjOlWu+OhAE5YVEqY0B3T2qb0enUi5x0zyZIq58koJJSG09nnGRdmJpf1kZBUZ3M4I6WpL3kvO4jsKukqtk8eGJ8cl2VHNIUWR7iNrWnwJiqXqWmLzPe1X2Qgyq8k/rMktojU5FIgkInpntqqxOtmj0ONX3GQbNExh75uKFJza42gjH1d5Y9HIQzVvbAkIp7LAgNd4Jit/BfKA/sGh8aTmkhU2OqrsEnDtX8tMAbofimBTmJtOU7RHPdvW203GVSC4LSSCMYgYpGDYsz2C/ZIpxwZTgkJeRZ9IrrUanIx7/b/BgQioS3RhHbpOQyI51OnlvXfQHBXY+4j8GMWokBUwzGEcupkvhr7vXeQ9sFC40gG1Pq1CxNQ9ajy2gfs4zEodHFM61rN9O+8JqvEEuJnblwUq92bTAc1DkDMrhHTX3pK80RCosugObFdhcFOFGbH/+7Q+nfEwCRPP7ampdpw2G3URfxBpKQFEmHZXqOW7igUQ5+1nChXyblZ8pt/J3IpvUTddjlhFzuy8m7HWEJYgtiSvS2OpbPtz7n631GQn0IyAVDCq5Q6RMe84SWJzikvm8A9204GgRNxOYvU=
    skip_cleanup: true
    on:
      tags: true
